# Generated by Django 4.1.2 on 2022-12-06 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptableCat',
            fields=[
                ('finnId', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('hasDistemperShots', models.BooleanField(default=False)),
                ('hasRabiesVax', models.BooleanField(default=False)),
                ('snapTested', models.BooleanField(default=False)),
                ('isFixed', models.BooleanField(default=False)),
                ('isAvailable', models.BooleanField(default=False)),
                ('birthDate', models.DateField()),
                ('intakeDate', models.DateField()),
                ('adoptDate', models.DateField(blank=True, null=True)),
                ('deathDate', models.DateField(blank=True, null=True)),
                ('coatDescription', models.TextField()),
                ('genDescription', models.TextField()),
                ('adoptedName', models.CharField(blank=True, max_length=40)),
                ('adoptionFee', models.PositiveSmallIntegerField(blank=True)),
                ('sex', models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=1)),
                ('healthConditionStatus', models.CharField(choices=[('H', 'healthy'), ('C', 'has a condition, no adverse effects'), ('A', 'has a condition with adverse effects')], default='H', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='CatPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.TextField()),
                ('caption', models.TextField(blank=True)),
                ('cats', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pictures', to='adopt.adoptablecat')),
            ],
        ),
    ]
