# Generated by Django 4.1.2 on 2022-12-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptablecat',
            name='dobApproximated',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='adoptablecat',
            name='coatDescription',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='adoptablecat',
            name='genDescription',
            field=models.TextField(blank=True),
        ),
    ]
